name: Release

on:
  release:
    types: [ "created" ]
  workflow_dispatch:

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  macos-arm64:
    name: macOS arm64
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Download MacPorts
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "macports/macports-base"
          latest: true
          fileName: "*-14-Sonoma.pkg"
          out-file-path: "/tmp"

      - name: Install MacPorts
        run: sudo installer -pkg /tmp/MacPorts-*.pkg -target /

      - name: Add MacPorts to PATH
        run: echo "/opt/local/bin:/opt/local/sbin" >> $GITHUB_PATH

      - name: Install CMake and GCC
        run: sudo port install cmake gcc12 gcc_select

      - name: Configure GCC
        run: sudo port select --set gcc mp-gcc12

      - name: Set Parallel Level
        run: echo "CMAKE_BUILD_PARALLEL_LEVEL=$(sysctl -n hw.logicalcpu)" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/dist/arm-webos-linux-gnueabi_sdk-buildroot
        env:
          CC: '/opt/local/bin/gcc'
          CXX: '/opt/local/bin/g++'

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build

      - name: Make Tarball
        run: |
          cmake -E tar cjvf arm-webos-linux-gnueabi_sdk-buildroot_darwin-x86_64.tar.bz2 \
            arm-webos-linux-gnueabi_sdk-buildroot
        working-directory: ${{github.workspace}}/build/dist

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.tagName.outputs.tag }}
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: ${{github.workspace}}/build/dist/arm-webos-linux-gnueabi_sdk-buildroot_darwin-x86_64.tar.bz2
